### ISSUE TITLE
plugin doesn't work with HEAD or latest nightly

### ISSUE THREAD

**Issue by marianoguerra** [tsloughter/rebar3_run#1]
it works with a build from rebar I have from some days ago.

how do I provide you with some debugging info? DEBUG=1 doesn't seem to provide much context

**Comment by marianoguerra** [comment]
just to be clearer, it doesn't work if you follow this example:

http://efene.org/guides/cowboy-rest-json.html

**Comment by marianoguerra** [comment]
this is the version where it works:

```
     Rebar3 report
 version 3.0.0-alpha-5
 generated at 2015-06-01T22:16:45+00:00
=================
Please submit this along with your issue at https://github.com/rebar/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: 
Entered as:

-----------------
Operating System: x86_64-redhat-linux-gnu
ERTS: Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]
Root Directory: /usr/lib64/erlang
Library directory: /usr/lib64/erlang/lib
-----------------
Loaded Applications:
common_test: 1.9
compiler: 5.0.3
crypto: 3.4.2
erlware_commons: 0.11.1+build.16.refef0d252
eunit: 2.2.9
inets: 5.10.4
kernel: 3.1
providers: 0.1.0
relx: 2.0.0+build.4.ref74fec34
sasl: 2.4.1
stdlib: 2.3
syntax_tools: 1.6.17
tools: 2.7.1

-----------------
Escript path: /home/mariano/bin/rebar3
Providers:
  app_discovery as clean compile cover ct deps dialyzer do edoc escriptize eunit help install_deps lock new pkgs release report shell tar unlock update upgrade version x
```

**Comment by tsloughter** [comment]
What does it do? Crash or hang?

**Comment by marianoguerra** [comment]
@tsloughter it doesn't run the code, just tried following this guide: http://efene.org/guides/cowboy-rest-json.html

and I get  this:

```
$ ./rebar3 run
===> Fetching rebar3_efene_compile ({git,
                                        "https://github.com/efene/rebar3_efene_compile.git",
                                        {branch,"master"}})
===> Fetching efene ({git,"git://github.com/efene/efene",
                             {branch,"master"}})
===> Compiling efene
===> Compiling rebar3_efene_compile
===> Fetching rebar3_efene_ct ({git,
                                   "https://github.com/efene/rebar3_efene_ct.git",
                                   {branch,"master"}})
===> Compiling rebar3_efene_ct
===> Fetching rebar3_run ({git,"git://github.com/tsloughter/rebar3_run.git",
                                  {branch,"master"}})
===> Compiling rebar3_run
make: Entering directory '/home/mariano/fn/myrestapp/_build/default/plugins/rebar3_run/c_src'
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/lib64/erlang/erts-6.3/include/ -I /usr/lib64/erlang/lib/erl_interface-3.7.20/include  -c -o /home/mariano/fn/myrestapp/_build/default/plugins/rebar3_run/c_src/rebar3_run.o /home/mariano/fn/myrestapp/_build/default/plugins/rebar3_run/c_src/rebar3_run.c
cc /home/mariano/fn/myrestapp/_build/default/plugins/rebar3_run/c_src/rebar3_run.o -shared -L /usr/lib64/erlang/lib/erl_interface-3.7.20/lib -lerl_interface -lei -o /home/mariano/fn/myrestapp/_build/default/plugins/rebar3_run/c_src/../priv/rebar3_run.so
make: Leaving directory '/home/mariano/fn/myrestapp/_build/default/plugins/rebar3_run/c_src'
===> Verifying dependencies...
===> Fetching cowboy ({git,"https://github.com/ninenines/cowboy.git",
                              {branch,"master"}})
===> Fetching jsx ({git,"https://github.com/talentdeficit/jsx.git",
                           {tag,"v2.5.2"}})
===> Fetching cowlib ({git,"git://github.com/ninenines/cowlib.git",
                              "1.3.0"})
===> Compiling jsx
===> Compiling ranch
===> Compiling cowboy
Compiling /home/mariano/fn/myrestapp/src/myrestapp_app.fn

Compiling /home/mariano/fn/myrestapp/src/myrestapp_handler.fn

Compiling /home/mariano/fn/myrestapp/src/myrestapp_sup.fn

===> Compiling myrestapp
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
      /home/mariano/fn/myrestapp/_build/default/lib
      /home/mariano/fn/myrestapp/ebin
      /usr/lib64/erlang/lib
===> Missing beam file megaco_flex_scanner <<"/usr/lib64/erlang/lib/megaco-3.17.3/ebin/megaco_flex_scanner.beam">>
===> Resolved myrestapp-0.0.1
===> Dev mode enabled, release will be symlinked
===> release successfully created!

~/fn/myrestapp ⌚ 17:21:56
```

with this env:

```
$ ./rebar3 report run
Rebar3 report
 version 3.0.0-alpha-6
 generated at 2015-06-15T15:22:02+00:00
=================
Please submit this along with your issue at https://github.com/rebar/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: run
Entered as:
  run
-----------------
Operating System: x86_64-redhat-linux-gnu
ERTS: Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]
Root Directory: /usr/lib64/erlang
Library directory: /usr/lib64/erlang/lib
-----------------
Loaded Applications:
common_test: 1.9
compiler: 5.0.3
crypto: 3.4.2
erlware_commons: 0.12.0
eunit: 2.2.9
inets: 5.10.4
kernel: 3.1
providers: 0.1.0
relx: 2.0.0+build.4.ref74fec34
sasl: 2.4.1
stdlib: 2.3
syntax_tools: 1.6.17
tools: 2.7.1

-----------------
Escript path: /home/mariano/fn/myrestapp/rebar3
Providers:
  app_discovery as clean compile compile cover ct ct deps dialyzer do edoc escriptize eunit help install_deps lock new pkgs release report run shell tar unlock update upgrade version xref 
```

**Comment by marianoguerra** [comment]
If I run:

```
~/fn/myrestapp/_build/default/rel/myrestapp ⌚ 17:36:00
$ ./bin/myrestapp console
```

by hand it works

**Comment by marianoguerra** [comment]
tried with latest nightly, got this:

```
===> Undefined call to provider's do function:
[{rebar3_run,do,
  [{state_t,"/home/mariano/fn/myrestapp",
    {dict,16,16,16,8,80,48,
     {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
     {{[],
       [[{deps,default},
     {cowboy,
      {git,"https://github.com/ninenines/cowboy.git",{branch,"master"}}},
     {jsx,{git,"https://github.com/talentdeficit/jsx.git",{tag,"v2.5.2"}}},
     {<<"cowboy">>,
      {git,"https://github.com/ninenines/cowboy.git",
       {ref,"341f991d58fde702f68fa9d0076ad6dc2f942917"}},
      0},
     {<<"jsx">>,
      {git,"https://github.com/talentdeficit/jsx.git",
       {ref,"327f0d2875676e17ed1cdff803df62ac85fd648c"}},
      0}],
    [{plugins,default},
     {rebar3_efene_compile,".*",
      {git,"https://github.com/efene/rebar3_efene_compile.git",
       {branch,"master"}}},
     {rebar3_efene_ct,".*",
      {git,"https://github.com/efene/rebar3_efene_ct.git",
       {branch,"master"}}},
     {rebar3_run,".*",
      {git,"git://github.com/tsloughter/rebar3_run.git",
       {branch,"master"}}}],
    [{locks,default},
     {<<"ranch">>,
      {git,"git://github.com/ninenines/ranch.git",
       {ref,"adf1822defc2b7cfdc7aca112adabfa1d614043c"}},
      1},
     {<<"cowlib">>,
      {git,"git://github.com/ninenines/cowlib.git",
       {ref,"14e597baa42a436469f99661ed7994685e269dc2"}},
      1},
     {<<"jsx">>,
      {git,"https://github.com/talentdeficit/jsx.git",
       {ref,"327f0d2875676e17ed1cdff803df62ac85fd648c"}},
      0},
     {<<"cowboy">>,
      {git,"https://github.com/ninenines/cowboy.git",
       {ref,"341f991d58fde702f68fa9d0076ad6dc2f942917"}},
       {event_handler,undefined,"event_handler",string,
    "Event handlers to attach to the runner"},
       {include,undefined,"include",string,"Include folder"},
       {abort_if_missing_suites,undefined,"abort_if_missing_suites",
    {boolean,true},
    "Abort if suites are missing"},
       {multiply_timetraps,undefined,"multiply_timetraps",integer,[]},
       {scale_timetraps,undefined,"scale_timetraps",boolean,[]},
       {create_priv_dir,undefined,"create_priv_dir",string,[]},
       {repeat,undefined,"repeat",integer,"How often to repeat tests"},
       {duration,undefined,"duration",string,"Max runtime (format: HHMMSS)"},
       {until,undefined,"until",string,"Run until (format: HHMMSS)"},
       {force_stop,undefined,"force_stop",string,"Force stop after time"},
       {basic_html,undefined,"basic_html",boolean,"Show basic HTML"},
       {ct_hooks,undefined,"ct_hooks",string,[]},
       {auto_compile,undefined,"auto_compile",{boolean,false},[]},
       {verbose,118,"verbose",boolean,"Verbose output"}],
      [test],
      default},
     {provider,clean,rebar_prv_clean,
      {[],[]},
      true,
      [app_discovery],
      "Remove compiled beam files from apps.",
      "Remove compiled beam files from apps.","rebar3 clean",
      [{all,97,"all",undefined,"Clean all apps include deps"}],
      [default],
      default},
     {provider,as,rebar_prv_as,
      {[],[]},
      true,[],
      "Higher order provider for running multiple tasks in a sequence as a certain profiles.",
      "Higher order provider for running multiple tasks in a sequence as a certain profiles.",
      "rebar3 as <profile1>,<profile2>,... <task1>, <task2>, ...",
      [{profile,undefined,undefined,string,"Profiles to run as."}],
      [default],
      default},
     {provider,app_discovery,rebar_prv_app_discovery,
      {[],[]},
      false,[],[],[],[],[],
      [default],
      default}]}],
  []},
 {rebar_core,do,2,
  [{file,
    "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
   {line,124}]},
 {rebar3,main,1,
  [{file,
    "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
   {line,47}]},
 {escript,run,2,[{file,"escript.erl"},{line,752}]},
 {escript,start,1,[{file,"escript.erl"},{line,276}]},
 {init,start_it,1,[]},
 {init,start_em,1,[]}]
===> Undefined command run in namespace default
```

**Comment by tsloughter** [comment]
Should be fixed now.

**Comment by marianoguerra** [comment]
is there a way for me to modify the code in place and have it recompiled? I tried running rebar3 clean; rebar3 compile inside _build/default/plugins/rebar3_run but the changes don't seem to take effect, if there's a way I can give you more precise information let me know.

I'm getting this:

```
===> sh info:
    cwd: "/home/mariano/fn/myrestapp"
    cmd: cp -R /home/mariano/fn/myrestapp/ebin/myrestapp_app.beam /home/mariano/fn/myrestapp/ebin/myrestapp_handler.beam /home/mariano/fn/myrestapp/ebin/myrestapp_sup.beam "/home/mariano/fn/myrestapp/_build/default/lib/myrestapp/ebin"

===>    opts: [{use_stdout,false},abort_on_error]

===> Port Cmd: cp -R /home/mariano/fn/myrestapp/ebin/myrestapp_app.beam /home/mariano/fn/myrestapp/ebin/myrestapp_handler.beam /home/mariano/fn/myrestapp/ebin/myrestapp_sup.beam "/home/mariano/fn/myrestapp/_build/default/lib/myrestapp/ebin"
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> Compiling myrestapp
===> erl_opts [debug_info,debug_info]
===> Files to compile first: []
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
      /home/mariano/fn/myrestapp/_build/default/lib
      /home/mariano/fn/myrestapp/ebin
      /usr/lib64/erlang/lib
      /home/mariano/fn/myrestapp/_build/default/rel

===> Missing beam file megaco_flex_scanner <<"/usr/lib64/erlang/lib/megaco-3.17.3/ebin/megaco_flex_scanner.beam">>
===> Resolved myrestapp-0.0.1
===> release successfully created!
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: undef
===> Stack trace to the error location: [{rebar3_run,do,
                                             [...],
                                             []},
                                            {rebar_core,do,2,
                                             [{file,
                                               "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                              {line,124}]},
                                            {rebar3,main,1,
                                             [{file,
                                               "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar3.erl"},
                                              {line,47}]},
                                            {escript,run,2,
                                             [{file,"escript.erl"},
                                              {line,752}]},
                                            {escript,start,1,
                                             [{file,"escript.erl"},
                                              {line,276}]},
                                            {init,start_it,1,[]},
                                            {init,start_em,1,[]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
```

**Comment by marianoguerra** [comment]
the report command:

```
$ ./rebar3 report run
Rebar3 report
 version 3.0.0-beta-1
 generated at 2015-07-15T09:41:11+00:00
=================
Please submit this along with your issue at https://github.com/rebar/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: run
Entered as:
  run
-----------------
Operating System: x86_64-redhat-linux-gnu
ERTS: Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]
Root Directory: /usr/lib64/erlang
Library directory: /usr/lib64/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.0.3
common_test: 1.9
compiler: 5.0.3
crypto: 3.4.2
erlware_commons: 0.13.0
eunit: 2.2.9
inets: 5.10.4
kernel: 3.1
providers: 1.4.1
relx: 3.3.0
sasl: 2.4.1
stdlib: 2.3
syntax_tools: 1.6.17
tools: 2.7.1

-----------------
Escript path: /home/mariano/fn/myrestapp/rebar3
Providers:
  app_discovery as clean compile compile cover ct ct deps dialyzer do edoc escriptize eunit help install_deps list lock new pkgs release relup report run shell tar unlock update upgrade upgrade version xref 
```

**Comment by tsloughter** [comment]
Hm, damn, I was getting that undef until I fixed where the nif was loaded. 

Can you delete `_build/default/plugins/rebar3_run` and use `{plugins, [rebar3_run]}` instead of the git repo and try again?

**Comment by marianoguerra** [comment]
it still fails (I have other two plugins there)

it's fetching this:

```
===> Fetching rebar3_run ({pkg,<<"rebar3_run">>,<<"0.1.0">>})
```

this is my rebar.config:

```
{erl_opts, [debug_info]}.
{deps, [
    {cowboy, {git, "https://github.com/ninenines/cowboy.git", {branch, "master"}}},
    {jsx, {git, "https://github.com/talentdeficit/jsx.git", {tag, "v2.5.2"}}}
]}.
{plugins, [
    {rebar3_efene_compile, ".*", {git, "https://github.com/efene/rebar3_efene_compile.git", {branch, "master"}}},
    {rebar3_efene_ct, ".*", {git, "https://github.com/efene/rebar3_efene_ct.git", {branch, "master"}}},
    rebar3_run
]}.
{provider_hooks, [{pre, [{ct, {efene, ct}}, {compile, {efene, compile}}]}]}.

{relx, [{release, { myrestapp, "0.0.1"}, ["myrestapp"]},
    {dev_mode, true},
    {include_erts, false},
    {extended_start_script, true}]}.

{profiles, [{prod, [{relx, [{dev_mode, false} ,{include_erts, true}]}]}]}.
```

**Comment by marianoguerra** [comment]
copy pasting the following you can replicate exactly my setup (if you already have the templates folder it would be good to remove it just in case)

```
mkdir -p ~/.config/rebar3/templates
git clone https://github.com/efene/rebar3_efene_template_rest_app.git ~/.config/rebar3/templates/fn_rest_app
mkdir myrestapp
cd myrestapp
wget https://s3.amazonaws.com/rebar3/rebar3
chmod u+x rebar3
./rebar3 new fn_rest_app name=myrestapp
./rebar3 run
```

**Comment by tsloughter** [comment]
Just ran those steps and it worked for me. And damn, you are on Linux? Was hoping maybe it was just something about you using OSX :)

I'm hoping some others try today so I can find out if it only works for me or not...

**Comment by marianoguerra** [comment]
I'm on Fedora 22, I will try now on ubuntu

**Comment by marianoguerra** [comment]
same error on ubuntu 15.04, maybe you have something on the path that I don't?

**Comment by marianoguerra** [comment]
report:

```
vagrant@vagrant-ubuntu-vivid-64:~/tmp/myrestapp$ ./rebar3 report run
Rebar3 report
 version 3.0.0-beta-1
 generated at 2015-07-15T14:22:18+00:00
=================
Please submit this along with your issue at https://github.com/rebar/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: run
Entered as:
  run
-----------------
Operating System: x86_64-pc-linux-gnu
ERTS: Erlang/OTP 17 [erts-6.2] [source] [64-bit] [async-threads:0] [kernel-poll:false]
Root Directory: /usr/lib/erlang
Library directory: /usr/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.0.3
common_test: 1.8.2
compiler: 5.0.2
crypto: 3.4.1
erlware_commons: 0.13.0
eunit: 2.2.8
inets: 5.10.3
kernel: 3.0.3
providers: 1.4.1
relx: 3.3.0
sasl: 2.4.1
stdlib: 2.2
syntax_tools: 1.6.16
tools: 2.7

-----------------
Escript path: /home/vagrant/tmp/myrestapp/rebar3
Providers:
  app_discovery as clean compile compile cover ct ct deps dialyzer do edoc escriptize eunit help install_deps list lock new pkgs release relup report run shell tar unlock update upgrade upgrade version xref 
```

**Comment by tsloughter** [comment]
Actually, yes! I just duplicated. I had still had it in my global config and global plugins install.

**Comment by tsloughter** [comment]
Wait, I lied, it works as a local plugin as well, it is simply when as a local plugin with your example does it fail.

So I'm guessing it has something to do with your other plugins.. Still working on figuring out why/how.

**Comment by tsloughter** [comment]
Argh, I figured it out. It is an issue with hooks removing plugins from the code path. This works fine unless another plugin is being used directly -- like in the case of `run`, it knows to add back the plugins if another hook is run, but not when running a provider directly.

Working on a fix.

**Comment by tsloughter** [comment]
@marianoguerra should be fixed in https://github.com/rebar/rebar3/pull/613

**Comment by marianoguerra** [comment]
works, thanks! :+1:
